apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "VirtoCommerce-Platform.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "VirtoCommerce-Platform.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "VirtoCommerce-Platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "VirtoCommerce-Platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
           - name: config-volume
             mountPath: /opt/virtocommerce/platform/appsettings.json
             subPath: appsettings.json
           - name: modules-volume
             mountPath: /opt/virtocommerce/platform/modules
           - name: appdata-volume
             mountPath: /opt/virtocommerce/platform/app_data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: vc-platfrom-appsettings
            items:
             - key: appsettings.json
               path: appsettings.json
        - name: modules-volume
          hostPath:
            path: /data/vc-platform-modules/
            type: DirectoryOrCreate
        - name: appdata-volume
          hostPath:
            path: /data/vc-platform-appdata/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
